language: java

install:
  - mvn clean verify
  - docker-compose build
  - docker login -u $Login -p $Password
  - docker tag sample-application-students_api maximefrelin/sample-api
  - docker tag sample-application-students_db maximefrelin/sample-db
  - docker push maximefrelin/sample-api
  - docker push maximefrelin/sample-db

addons:
  sonarcloud:
    organization: "maximefrelin"
    token:
      secure: "uH9iRhuhCliBXuaqTCuZpIM4hEo20f/Rw2wPHcNzQRu+4u+m/NSiH6270fSpIXkZ8rNL0iDHDnbBTnwcyTa14cxlGT9yG+pVmE8tvMGtDab5vAa6tXwvyFELnDVpWli732gh5YIR9At7opn9YelkaxAA3LQ+ZVBInHySb9jQNL6+hu/eEPZgP+ICG+NrYARkh5uNlntHVzGJ7xncxgjlY6RKgO566/cG3fdybBIRryPyAv+XZSXpt9FDFLFRktBOfj9TmOiRObEL713Zkqu2XrAqkgQ5kHlcKmCxeUj1wujBq6F6Y2MyhgJTsR6rO5CSYcseZbjx4iOzNNPFpHKvgryii0P95CcjLkRMknMYtI9KNtgCZlvi83X2mntXkhQyIuXN96lx5e0wJHUApcL3VpOMDD2UF5mK8GTRXGIIsiWYYBv5WLzxHrZgxkZPOoXbSFkfcsh2N7DZ1VGOlb8OouJYzjiXN2xDJqZUuv43ihXNwseQaRkb0UzWzQpkRZZ4jAfi7WZn3JyMu19PeFbBHsT3k2Vh2JBIcyn3tBnHaDVBRaHl9Ex2Vt39K9MSjF0LiNY7c4jUzdyotrIf+hVW75b8wyQIxihfqmpnKK/70H+6uiQ9WlVcfH/ZBedsLC+YKe3xn6B5gqtOKoc5nU7w7iSc/2iQnDToK9KDaNd3D5Q=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner -X
