language: java

install:
  - mvn clean verify
  - docker-compose build
  - docker login -u $Login -p $Password
  - docker tag sample-application-students_api maximefrelin/sample-api
  - docker tag sample-application-students_db maximefrelin/sample-db
  - docker push maximefrelin/sample-api
  - docker push maximefrelin/sample-db

addons:
  sonarcloud:
    organization: "maximefrelin"
    token:
      secure: "DFFDV8UAoeFEF3Rej1RQTOsVkgRQM+ztaMZ1s64Is7ooWCE7i6glOV6Dd63mdhliKhZ3kzoEpaCLWjQmHrw8aRtkwK+0uoirO/Q8W7wA6FhI0ZtUcpxEetmhR6JtNslZgAf6CwYXYmLoISuqfq4HBVJsrzEJ97ImW6/+1kQDjb1SE5+B+NI+bpvl9b+MbyvOgbacqNbHIZLVm8dM60zn3BEBh/hBuMsCZOMTePxBNwg3fL+XCBIeky/RcVEnRo8r8LxQdyqBpkSWMlTIH/SiZpcn5bg0AXD5FO5Vxz6+rDmx6gXlJqcDgsKRBG1+VvIEr2K3Awej8fQLGn1G6+zWj8nFDzB5OqkD7yzz9smzGODTQEOVldISa225s/maPxyJGiffZ5sL8/0029rd1NsH3n0gyEsa81ap13qWwXCp9Lwxu2JS4rLEoNCl4ExL1L/C2HabJJB7naUteXPopNR8qYFyFVtL6ccXYtEB0mSD/FylWe7CHdLQHbIPj9Bga5/LWCQo7SvB6Mzwt0wzf3FAFObm90vaIIu6V1vI4mI2JiQaft1BwI8LLfCYALhpK55lPWVmdITRPJg5V9G6nQM6aDz1U0L1xNP67xWy+vNO7HKTQRCCxqOk7Vs1NraWknkzNB8GE/1E+XKiHx0BF87vdOAovmiofSn1geKKFAfRK/A=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
