language: java

install:
  - mvn clean verify
  - docker-compose build
  - docker login -u $Login -p $Password
  - docker tag sample-application-students_api maximefrelin/sample-api
  - docker tag sample-application-students_db maximefrelin/sample-db
  - docker push maximefrelin/sample-api
  - docker push maximefrelin/sample-db

addons:
  sonarcloud:
    organization: "maximefrelin"
    token:
      secure: "Br7zFDqNCUKLpppPBHs9z6Phii4mAkO+nE+exLYbUHwbFJ142gMI1D1IQ6erdJexORy1hmdmpz4jvTfHSKjocNE7iXZfFPunHSErjmkOXfmla6cX7zrEMXPfhowMwjXXRW6mclnJshfs/xpdQQTusVf7siibVaoo9Z2zhwe9kjNz6DleBPoGsJ/iMbtFCQGTGM1zAi87u1PeyXiC9KyTjEm49kP+290a0HEjoRDCsZPz38hOh/1qid982okQumxiSplTa4q2eEUfYcMnFRFPukkPXNvohQmRpqMApDBKgIaKtsE/kF/BWnymV0UEoXaDsRof6DnrB1e1jcJE2pRIMYScZWUC2hhJc8nCRNHB0GzM8E1baMnPTcSFzj/xDl3uS9UBcG+UrdN9tTrVudxn9zmEK9n3puVOCgPkj+dD+EmombexDnuervo5lofkDzyUP6Lc3PsgwLtbqrZVdWGdsPYY0R9yMRug3d2y9mqYX65B7wPrpgQnGkIaRuFAXZieLR98Zga7XE6BQlEjMEIUXvUMMzbSF9ejmjWQkn8lulx0xYaLWcKbP5DDSpo/G87movnE/K62FCNxVaAhtBVVciyRAV3KhYT6QDQwoS6RuB1PaHhTxo7bJoxFn8oddrYuPC8p0zpwxC/Ys8JbHeSzw+oKGhlm2oVlqmquh4kz4MY="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn install sonar:sonar -Dsonar.projectKey=MaximeFrelin_sample-application-students -Dsonar.branch.name=$CI_COMMIT_REF_NAME
